version: '3'

services:
  nexus:
    image: sonatype/nexus3:latest
    container_name: nexus
    ports:
      - "8081:8081"
      - "5000:5000"
    volumes:
      - ./data:/nexus-data
    environment:
      - INSTALL4J_ADD_VM_PARAMS=-Xms2g -Xmx2g
      - Djava.util.prefs.userRoot=/opt/sonatype/sonatype-work/nexus3
      - Djava.util.prefs.systemRoot=/opt/sonatype/sonatype-work/nexus3
networks:
  default:
    external:
      name: nexus-network
