apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yaml -n nexus --controller statefulset convert
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: nexus
  name: nexus
  namespace: nexus
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nexus
  serviceName: nexus
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.network/nexus-network: "true"
        io.kompose.service: nexus
    spec:
      containers:
        - env:
            - name: INSTALL4J_ADD_VM_PARAMS
              value: -Xms2g -Xmx2g
          image: sonatype/nexus3:latest
          name: nexus
          ports:
            - containerPort: 8081
              hostPort: 8081
              protocol: TCP
            - containerPort: 5000
              hostPort: 5000
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /nexus-data
              name: nexus-claim0
      restartPolicy: Always
  updateStrategy: {}
  volumeClaimTemplates:
    - metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: nexus-claim0
        name: nexus-claim0
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 100Mi
      status: {}
status:
  availableReplicas: 0
  replicas: 0
