apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yaml -n nexus --controller statefulset convert
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: nexus
  name: nexus
  namespace: nexus
spec:
  clusterIP: None
  ports:
    - name: "8081"
      port: 8081
      targetPort: 8081
    - name: "5000"
      port: 5000
      targetPort: 5000
  selector:
    io.kompose.service: nexus
  type: ClusterIP
status:
  loadBalancer: {}
